SELECT 
    "caracteristiques_geocoded_3_postgis"."Num_Acc" AS "Num_Acc",
    "caracteristiques_geocoded_3_postgis"."an" AS "an",
    "caracteristiques_geocoded_3_postgis"."mois" AS "mois",
    "caracteristiques_geocoded_3_postgis"."jour" AS "jour",
    "caracteristiques_geocoded_3_postgis"."hrmn" AS "hrmn",
    "caracteristiques_geocoded_3_postgis"."lum" AS "lum",
    "caracteristiques_geocoded_3_postgis"."agg" AS "agg",
    "caracteristiques_geocoded_3_postgis"."int" AS "int",
    "caracteristiques_geocoded_3_postgis"."atm" AS "atm",
    "caracteristiques_geocoded_3_postgis"."col" AS "col",
    "caracteristiques_geocoded_3_postgis"."com" AS "com",
    "caracteristiques_geocoded_3_postgis"."adr" AS "adr",
    "caracteristiques_geocoded_3_postgis"."gps" AS "gps",
    "caracteristiques_geocoded_3_postgis"."lat" AS "lat",
    "caracteristiques_geocoded_3_postgis"."long" AS "long",
    "caracteristiques_geocoded_3_postgis"."dep" AS "dep",
    "caracteristiques_geocoded_3_postgis"."date" AS "date",
    "caracteristiques_geocoded_3_postgis"."original_city_code" AS "original_city_code",
    "caracteristiques_geocoded_3_postgis"."original_name" AS "original_name",
    "caracteristiques_geocoded_3_postgis"."current_city_code" AS "current_city_code",
    "caracteristiques_geocoded_3_postgis"."current_name" AS "current_name",
    "caracteristiques_geocoded_3_postgis"."ban_citycode" AS "ban_citycode",
    "caracteristiques_geocoded_3_postgis"."ban_label" AS "ban_label",
    "caracteristiques_geocoded_3_postgis"."ban_latitude" AS "ban_latitude",
    "caracteristiques_geocoded_3_postgis"."ban_longitude" AS "ban_longitude",
    "caracteristiques_geocoded_3_postgis"."ban_postcode" AS "ban_postcode",
    "caracteristiques_geocoded_3_postgis"."ban_score" AS "ban_score",
    "caracteristiques_geocoded_3_postgis"."ban_type" AS "ban_type",
    "caracteristiques_geocoded_3_postgis"."bano_citycode" AS "bano_citycode",
    "caracteristiques_geocoded_3_postgis"."bano_label" AS "bano_label",
    "caracteristiques_geocoded_3_postgis"."bano_latitude" AS "bano_latitude",
    "caracteristiques_geocoded_3_postgis"."bano_longitude" AS "bano_longitude",
    "caracteristiques_geocoded_3_postgis"."bano_postcode" AS "bano_postcode",
    "caracteristiques_geocoded_3_postgis"."bano_score" AS "bano_score",
    "caracteristiques_geocoded_3_postgis"."bano_type" AS "bano_type",
    "caracteristiques_geocoded_3_postgis"."ban2_citycode" AS "ban2_citycode",
    "caracteristiques_geocoded_3_postgis"."ban2_label" AS "ban2_label",
    "caracteristiques_geocoded_3_postgis"."ban2_latitude" AS "ban2_latitude",
    "caracteristiques_geocoded_3_postgis"."ban2_longitude" AS "ban2_longitude",
    "caracteristiques_geocoded_3_postgis"."ban2_score" AS "ban2_score",
    "caracteristiques_geocoded_3_postgis"."ban2_type" AS "ban2_type",
    st_distance("IGN_COMMUNE_FRANCE".the_geom, st_point(long, lat)) as distance_commune_baac,
    st_distance("IGN_COMMUNE_FRANCE".the_geom, st_point(ban_longitude, ban_latitude)) as distance_commune_ban,
    st_distance("IGN_COMMUNE_FRANCE".the_geom, st_point(ban2_longitude, ban2_latitude)) as distance_commune_ban2,
    st_distance("IGN_COMMUNE_FRANCE".the_geom, st_point(bano_longitude, bano_latitude)) as distance_commune_bano,

    "IGN_COMMUNE_FRANCE"."CODE_COM" AS "CODE_COM"
  FROM "caracteristiques_geocoded_3_postgis"
  LEFT JOIN "ign_commune_france" "IGN_COMMUNE_FRANCE"
    ON "caracteristiques_geocoded_3_postgis"."current_city_code" = "IGN_COMMUNE_FRANCE"."INSEE_COM"